template: true
valuesFilePath: ./values.yml

resources:
  - name: git_repository
    type: GitRepo
    configuration:
      gitProvider: {{ .Values.gitProvider }}
      path: {{ .Values.repoPath }}

  - name: mvn_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: {{ .Values.artifactory }}

pipelines:
  - name: petclinic_monolith_pipeline
    steps:
      - name: maven_build_step
        type: MvnBuild
        configuration:
          mvnCommand: "clean install"
          resolverSnapshotRepo: {{ .Values.deployerRepo }}
          resolverReleaseRepo: {{ .Values.deployerRepo }}
          deployerSnapshotRepo: {{ .Values.deployerRepo }}
          deployerReleaseRepo: {{ .Values.deployerRepo }}
          integrations:
            - name: {{ .Values.artifactory }}
          inputResources:
            - name: git_repository
        execution:
          onStart:
            - echo "Starting the Maven build step"
          onSuccess:
            - echo "Maven build step succeeded"
          onFailure:
            - echo "Maven build step failed"
          onComplete:
            - echo "Maven build step completed"

      - name: publish_build
        type: PublishBuildInfo
        configuration:
          forceXrayScan: false
          inputSteps:
            - name: mvn_build_step
          outputResources:
            - name: mvn_build_info
