template: true
valuesFilePath: ./values.yml

resources:
  - name: git_repository
    type: GitRepo
    configuration:
      gitProvider: {{ .Values.gitProvider }}
      path: {{ .Values.repoPath }}
      buildOn:
        commit: true
      branches:
        include: {{ .Values.gitBranch }}
      tags:
        include: '-rc-\d*'
      cancelPendingRunsOn:
        newCommit: true
        pullRequest: true
        newTag: true

pipelines:
  - name: petclinic_monolith_pipeline
    steps:
      - name: mvn_build_step
        type: MvnBuild
        configuration:
          mvnCommand: "clean install"
          resolverSnapshotRepo: {{ .Values.deployerRepo }}
          resolverReleaseRepo: {{ .Values.deployerRepo }}
          deployerSnapshotRepo: {{ .Values.deployerRepo }}
          deployerReleaseRepo: {{ .Values.deployerRepo }}
          integrations:
            - name: {{ .Values.artifactory }}
          inputResources:
            - name: git_repository
        execution:
          onStart:
            - echo "Starting the Maven build step"
          onSuccess:
            - echo "Maven build step succeeded"
          onFailure:
            - echo "Maven build step failed"
          onComplete:
            - echo "Maven build step completed"

      - name: publish_build
        type: PublishBuildInfo
        configuration:
          forceXrayScan: false
          inputSteps:
            - name: mvn_build_step
          outputResources:
            - name: mvn_build_info
  - name: promote_to_stage_on_tag_create
    steps:
      - name: check_tag_event
        type: Bash
        configuration:
          inputResources:
            - name: git_repository
          integrations:
            - name: {{ .Values.gitProvider }}
          environmentVariables:
            GITHUB_REF: '${res_source_repo[0].commit.ref'
        execution:
          onStart:
            - |
              if [[ $GITHUB_REF == refs/tags/* ]]; then
                echo "Tag created"
                exit 0
              else
                echo "Not a tag"
                exit 1
              fi
      - name: perform_action_on_tag_create
        type: Bash
        configuration:
          inputResources:
            - name: mvn_build_info
        execution:
          onStart:
            - |
              echo "Performing action on tag create event..."
              # Add your custom actions or commands here          
          
